/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package automationcompany;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhinav
 */
public class CustomerPage extends javax.swing.JFrame {

    /** Creates new form CustomerPage */
    public CustomerPage() {
        initComponents();
    }
    
    
    public CustomerPage(String username){
    initComponents();
    lblUser.setText(username);
    
    
    }
    
    
    
  
            

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProduct = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOrderPlaced = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Online Product Shopping", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        lblProduct.setText("Select Product");

        lblQuantity.setText("Quantity");

        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product", "Laptop", "Mobile", "Mouse", "Printer", "Keyboard", "HDD", "SSD", "Pendrive", "Optical Disk", "RAM", "CPU Cabinet", "Graphic Card", "Monitor", "Speaker", "UPS" }));
        cmbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductActionPerformed(evt);
            }
        });

        lblPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(51, 51, 255));
        lblPrice.setText("Price ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Price "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setBackground(new java.awt.Color(0, 204, 204));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdd.setText("ADD TO CART");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 153, 153));
        btnRemove.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRemove.setText("Remove From Cart");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnOrderPlaced.setBackground(new java.awt.Color(0, 204, 102));
        btnOrderPlaced.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOrderPlaced.setText("Place Order");
        btnOrderPlaced.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrderPlaced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderPlacedActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblProduct)
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbProduct, 0, 168, Short.MAX_VALUE)
                                            .addComponent(txtQuantity))))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemove))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOrderPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduct)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPrice)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(btnRemove)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnOrderPlaced, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductActionPerformed
        
        String Product =(String) cmbProduct.getSelectedItem();
        int price,quantity;
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/automationdatabase?useTimezone=true&serverTimezone=UTC","root","");
        String sql1="SELECT * FROM product_order where product=?";
        
        PreparedStatement st;
        st=con.prepareStatement(sql1);
        st.setString(1, Product);
            ResultSet rs=st.executeQuery();
            while (rs.next()) { 
                price = rs.getInt("price");
                quantity=rs.getInt("quantity");
                if(quantity>0){
                lblPrice.setForeground(Color.blue);
                lblPrice.setText(String.valueOf(price));
                }else{                
                    lblPrice.setForeground(Color.red);
                    lblPrice.setText(String.valueOf(quantity));            
                }
                 }
                     
        
        }catch(ClassNotFoundException | SQLException ex){
        
            JOptionPane.showMessageDialog(null, ex);
           
        }
        
        
        
    }//GEN-LAST:event_cmbProductActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String Product=(String)cmbProduct.getSelectedItem();
        int quantity= Integer.parseInt(txtQuantity.getText());
        int Cost=Integer.parseInt(lblPrice.getText());
        int price;        
        price=quantity*Cost;
        
        Object data[] = {Product,quantity,price};
        DefaultTableModel tbl=(DefaultTableModel)jTable1.getModel();
        
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/automationdatabase?useTimezone=true&serverTimezone=UTC","root","");
        String sql="SELECT * from product_order where product=?";
        PreparedStatement st=con.prepareStatement(sql);
        st.setString(1, Product);
        ResultSet rs=st.executeQuery();
        
        while(rs.next()){
            if(rs.getInt("quantity")==0){
            JOptionPane.showMessageDialog(null, "Product is not in stock");
            
            }else{
                
                if(rs.getInt("quantity")<quantity){
                JOptionPane.showMessageDialog(null, "Selected Quantity is not in Stock");
                }else{ 
                    tbl.addRow(data);
                } 
            }
        }
        }catch(ClassNotFoundException | SQLException ex){
        
        
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
                DefaultTableModel tbl=(DefaultTableModel)jTable1.getModel();
                
            if(jTable1.getSelectedRow() != -1) {
               // remove selected row from the model
               tbl.removeRow(jTable1.getSelectedRow());
             
            }else if(jTable1.getSelectedRow() == -1){
                JOptionPane.showMessageDialog(null, "Please select item in the Cart");
            }
            
       
        
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOrderPlacedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderPlacedActionPerformed
      
        
       DefaultTableModel tbl=(DefaultTableModel)jTable1.getModel();
       String username=lblUser.getText();
       long rand =  (long) Math.floor(Math.random() *1552) + 128;
       String orderid=String.valueOf(rand);
      
       
       int total=0;
       
       
       if(tbl.getRowCount()==0){
       
          JOptionPane.showMessageDialog(this, "Table is empty");      
       
       }else{
          try{
              
          String product, quantity,price;
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/automationdatabase?useTimezone=true&serverTimezone=UTC","root","");
          
          String sql="SELECT * from userdetails where username=?";
          String query="insert into invoice(orderid,product,price,quantity,name,mobile,address) values(?,?,?,?,?,?,?) ";
          String query1="insert into sales(orderid,total) values(?,?)";
          
          PreparedStatement st1;
          PreparedStatement st2; 
          PreparedStatement st;
          
          
          st1=con.prepareStatement(sql);
          st=con.prepareStatement(query);
          st2=con.prepareStatement(query1);
          
          
          st1.setString(1, username);
          ResultSet rs=st1.executeQuery();
          if(rs.next()){
          
              //Get value from database
              String name = rs.getString("name");
              String mobile=rs.getString("mobile");
              String address=rs.getString("address");
              
              
         for(int i=0;i<tbl.getRowCount();i++){
      
         
          price=tbl.getValueAt(i, 2).toString();
          
          total=total+Integer.parseInt(price);
           System.out.println(total);
              }
           
          
          
              
            //Product_order  
         for(int i=0;i<tbl.getRowCount();i++){
      
          product=tbl.getValueAt(i, 0).toString();
          quantity=tbl.getValueAt(i, 1).toString();
          price=tbl.getValueAt(i, 2).toString();
          
          //insert into database
          st.setString(1, orderid);
          st.setString(2, product);
          st.setString(3, price);
          st.setString(4, quantity);
          st.setString(5, name);
          st.setString(6, mobile);
          st.setString(7, address);
          st.executeUpdate();
                 
         }
         st.addBatch();
         JOptionPane.showMessageDialog(this, "Oder Placed Successfull"+"\nYour Order ID is : "+orderid);
     //Sales  
     
       
      
       st2.setString(1, orderid);
       st2.setInt(2, total);
       st2.executeUpdate();
       st2.addBatch();
    
          
          }
          
      }catch(ClassNotFoundException | SQLException ex){ JOptionPane.showMessageDialog(null, ex);     }
       }
        
        
        
    }//GEN-LAST:event_btnOrderPlacedActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        
          
         int P = JOptionPane.showConfirmDialog(null, " Are you sure want to Logout ?", "Confirmation", JOptionPane.YES_NO_OPTION);

                if (P == 0){
                setVisible(false);
                }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderPlaced;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

}
